#vim:set nobomb:set encoding=utf-8
########################################
#	Brief	ddc.vim plugins
#	Author	KORYUOH
#	Create	2024/08/26
#	Update	2024/10/09
#	Version	1.14
#	Lazy : Not Lazy
########################################

[[plugins]]
repo = 'Shougo/ddc.vim'
depends='denops.vim'
on_event= ['InsertEnter','CmdlineEnter']
hooks_file = '$BASE_DIR/vim/ddc.vim'

## ===== DDC Sources

## UI
[[plugins]]
repo = 'Shougo/pum.vim'
hooks_file = '$BASE_DIR/vim/pum.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = 'pum.vim'
group = 'ddc'


[[plugins]]
repo = 'Shougo/ddc-ui-inline'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-ui-none'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-source-around'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-source-input'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-source-rg'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-source-line'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-source-vim'
group = 'ddc'

[[plugins]]
repo = 'matsui54/ddc-source-buffer'
group = 'ddc'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
group = 'ddc'

[[plugins]]
repo = 'Milly/ddc-source-register'
group = 'ddc'

## Matcher

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_length'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_length'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_vimregexp'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_prefix'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_suffix'
group = 'ddc'

## sorter

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_head'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_lsp_kind'
group = 'ddc'

## Converter

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_lsp_kind'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_truncate_abbr'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_kind_labels'
group = 'ddc'

[[plugins]]
repo = 'tani/ddc-fuzzy'
group = 'ddc'

[[plugins]]
repo = 'delphinus/ddc-ctags'
group =  'ddc'

# [[plugins]]
# depends = ['denops.vim']
# hooks_file = '$BASE_DIR/vim/ddc_skkeleton.vim'


